name: On push

on:
  push:

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: npm

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Test
      run: |
        npx playwright install
        npm run test
